# Generated by Django 5.0.6 on 2024-05-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
