# Generated by Django 5.0.4 on 2024-05-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('features', '0002_rename_feature_value_productfeature_feature_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='product',
        ),
        migrations.AddField(
            model_name='usercart',
            name='product_feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='features.productfeature'),
            preserve_default=False,
        ),
    ]
