# Generated by Django 5.0.4 on 2024-05-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfeature',
            old_name='feature_value',
            new_name='feature_values',
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product'),
        ),
    ]
