# Generated by Django 5.0.6 on 2024-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_featurevalue_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='feature_values',
            field=models.ManyToManyField(related_name='product_feature', to='features.featurevalue'),
        ),
    ]
